const tintColorLight = '#971d32';

export default {
  light: {
    invalidText: '#971D32',
    text: '#000',
    buttonTextColor: '#FFF',
    background: '#FFF',
    headerTitleColor: tintColorLight,
    tint: tintColorLight,
    tabBarBackground: '#FFF',
    tabBarBorder: '#DDD',
    tabIconDefault: '#CCC',
    tabIconSelected: tintColorLight,
    separator: '#000',
    inputBorder: '#BBB',
    inputLabel: '#888',
    buttonBackgroundColor: '#971D32',
    buttonDisabledBackgroundColor: '#D5D5D5',
  },
  dark: {
    invalidText: '#971D32',
    text: '#000',
    buttonTextColor: '#FFF',
    background: '#FFF',
    headerTitleColor: tintColorLight,
    tint: tintColorLight,
    tabBarBackground: '#FFF',
    tabBarBorder: '#DDD',
    tabIconDefault: '#CCC',
    tabIconSelected: tintColorLight,
    separator: '#000',
    inputBorder: '#BBB',
    inputLabel: '#888',
    buttonBackgroundColor: '#971D32',
    buttonDisabledBackgroundColor: '#D5D5D5',
  },
};
